# Generated by Django 2.1 on 2018-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20180813_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pwd',
            field=models.CharField(default='888888', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
